### PR TITLE
New JES/JER source files: VBF and monojet

### PR DESCRIPTION
**Pull request by alpakpinar**
This PR contains the new source files for JES/JER uncertainties after the smearing is turned back on. All variations are calculated with smearing turned on and JER variation is calculated two-sided, as previously.

### CODE REVIEW

**Comment by AndreasAlbert** [comment]
I am not certain now that we will use the JER smearing in monojet after all. Could you rename these files by adding a tag like "_jerSmearing"? That way, we can keep both files with and without JER smearing in the repository and switch on short notice if need be.

**Comment by alpakpinar** [comment]
Hey @AndreasAlbert , I now have both JER and non-JER files in sys, and a switch to decide which one is going to be used. Also a small merge conflict is fixed and force pushed.

**Comment by alpakpinar** [comment]
Hey @AndreasAlbert , now the changes are in place. For VBF categories, the smearing is applied automatically, for monojet it is the other way. I also added a message showing the input JES unc file being used. Let me know if you want any changes, thanks!

**Comment by AndreasAlbert** [comment]
Thanks, looks good!

**Pull request merged**
