### PR TITLE
use symmetrized version of jes jer tf uncertainties for monojet

### PR DESCRIPTION
**Pull request by siqiyyyy**

### CODE REVIEW

**Comment by siqiyyyy** [comment]
@AndreasAlbert I removed the abs() one line https://github.com/bu-cms/monox_fit/pull/71/files#diff-81931bd6ebd0867b6ddf8dc189473acedae572c6dc837dc7fb32687033f267b7R34
It was `abs(cont_up - 1 ) > abs(cont_down -1)` but I don't think the abs makes sense here. Can you confirm?

**Comment by AndreasAlbert** [comment]
Indeed, please remove the abs. Actually, can also remove the ```-1``` on both sides of the relation

**Comment by siqiyyyy** [comment]
I realize that there are also jerjes variations on MC shapes and the variations on VBF. Do we also want to symmetrize those?

**Comment by AndreasAlbert** [comment]
thanks for updating! the mc shape variations are really big, so no symmetrization is needed. let's leave vbf as is.

**Pull request merged**
